INSERT INTO users (user_name, first_name, last_name, email, password, profile_img_url, age, gender, height, weight, country, fitness_goal, diet_type, primary_workout, about_me, tips, future_goals, bmi)
  VALUES
  ('Joe Grewal', 'Joe', 'Grewal', 'grewaljoe20@gmail.com', 'password', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Man_25_weightgain.jpg?raw=true',
  28, 'male', 71, 200, 'Canada', 'weight gain', 'carnivore', 'strength training', 
  'Welcome! I originally started my fitness journey back during the early days of high school. I was very skinny at the time and was looking to put on some muscle to get stronger. I would quickly eat my packed lunch everyday and then use the school gym to lift weights for around 40min. I didn''t really know what I was doing at that time or have any sort of plan, but through consistency I started seeing results. Midway through high school I stopped being as consistent and eventually dropped my daily workouts after a period of time where the gym was closed for renovations. I didn’’t start working out on a consistent basis again until a few years after I finished high school. When I did eventually return to a daily workout routine, I changed my workouts from full body workouts to splits where I would target individual muscles on different days of the week.', 
  'Focus on consistency rather than intensity when working out (at least the beginning). Rather than burning yourself out with heavy workouts that leave you feeling very sore the next day, try lifting weights at about 70 percent of your max lifting capacity. Using this approach would make it easier for you to transform the act of working out into a daily habit as well as allowing you to focus more on proper lifting form/technique. Once it has become established as a habit, you can then look to increase  the intensity of workouts and also diversify the types of exercises in your routine.', 
  'To fix slight muscle imbalance between individual arms and put on 5-10 pounds of muscle mass while also burning off at least 10 pounds of fat. And adjusting my diet to include more healthy choices and less bad ones.',
  27.92
  ),
  ('Abby Ef',
  'Abby',
  'EF',
   'abby_faigao@yahoo.com',
    'password',
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Woman_30_strength.jpg?raw=true',
   40,
  'female',
  63,
    140,
  'USA',
  'weight loss',
  'low-carb',
  'strength training',
  'Before I began my weight-loss journey, I lacked confidence, motivation, and self-esteem. I hid in my house to avoid being seen by anyone who had known me before I gained weight. My self-isolation and lack of confidence was starting to affect my marriage and friendships. At 26, I hit my heaviest weight of 200 pounds. I had reflected on the past year and realized that it had consisted of going to work, then immediately coming home to just sit in the house with my husband and kids. I decided that night that I had had enough. I was going to start working on making myself feel and look better. After researching and trying different workouts programs and exercises, I found that I loved how my body reacted to lifting and targeted body sculpting. There were times where I indulged for days and weeks at a time. However, I never lost sight of my goal and the reasons why I wanted to lose weight and get healthier.',
  'Avoid sugar if possible(e.g., soft drinks, fruit juices, ice cream among many others). Limit intake of pasta, cereal and bread. Be careful with cheese and nuts, as it''s easy to overeat on them. Don''t eat more than one piece of fruit per day.',
  'To maintain discipline about my workout and diet. Do one outdoor workout per week. Try new group fitness class.',
  24.82
),
(
  'Shaun Robinson', 
  'Shaun', 
  'Robinson', 
  'connecshaun@gmail.com', 
  'fitness', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/man_40_weightloss.jpg?raw=true', 
  33, 
  'male', 
  71, 
  160, 
  'Canada', 
  'weight gain', 
  'other', 
  'hiit', 
  'Hi! A bit about me, well for starters, I enjoy food. I''m not interested in blacklisting anything from my diet. I KNOW, sugar is the worst thing ever and alcohol is just empty calories. But cookies are delicious, and I enjoy a glass of wine or three occasionally. Or some quality tequila, neat, because if you have to dress it up or chase it, you shouldn''t be drinking it. I am unapologetically lazy. I''m at a point in life where I don''t care to spend 2+ hours in the gym. After about an hour, I''d better see daylight. Also, three days a week is good for me. I used to get after it four and five days a week. I just don''t care that much anymore; I''ve got other things to do with my time. While keeping in mind the first two points, I still want maximum-ish results. I''m not interested in working unnecessarily hard and giving up a lot; I''m interested in working efficiently. I want seemingly disproportionate results. Note that I didn''t say I won''t ever have to work hard, just that I''m going to be smart about it.', 
  'In terms of health tips, I don''t have a ton of advice to give. I guess that''s part of the reason I am here looking for inspiration from others. But what I will say, is, if you have a plan, stick with it! If you take a few days off here and there and you get loose about it, that''s not a plan. Dedicate yourself!', 
  'I''m looking to gain about 5-10 pounds of muscle this year. I''d like to duplicate that next year as well and then after that my goal is to lean out to work towards a more defined physique.',
  22.34
  ), 
  (
  'El Jord', 
  'Ellie', 
  'Jordan', 
  'el_jord@gmail.com', 
  'password', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Man_25_weightloss.jpg?raw=true',
  26, 
  'male', 
  68.4, 
  138, 
  'Argentina', 
  'weight gain', 
  'other', 
  'strength training', 
  'As it is with being overweight, being skinny too invites a lot of hurtful comments and name calling. For some people, gaining weight can be just as difficult as losing weight is for others. For 3 straight years of my college, I had to get all my clothes stitched! With a waistline of 26 inches, I did not get any clothes of my size in the market. This made me feel really, really under confident. To add to my woes, I did not have a lot of friends back then. With this constantly in my mind, I decided to change my life. I enrolled in a gym, eat healthy. Odd or not, I keep seeing my old photographs to stay right on the fitness track, that what helps my motivation also. I feel a lot more confident now, which is very necessary for my profession. I''m a Physics Teacher by the way. The biggest fear of my life is going back to where I had started from  being the skinny self who hardly had any friends.', 
  'Although I needed to gain weight, I completely steered clear of oily and junk food. Instead, I opted for fresh fruits and vegetables, dry fruits and nuts. I increased the intake of fatty food in my diet, including milk and butter. I also ensured that I ate green vegetables which provided me with a sufficient amount of nutrients.',
  'I want to maintain the same physique, as of now. I would say to find more variations in my workout.',
  21
  ),
  (
  'Toni Kay', 
  'Toni', 
  'Kay', 
  'tkay@gmail.com', 
  'password', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Woman_30_pilates.jpg?raw=true',
  25, 
  'female', 
  63, 
  110, 
  'United Kingdom', 
  'endurance', 
  'keto', 
  'pilates', 
  'If the thought of doing Pilates every day conjures images of long-limbed celebs and eye-wateringly expensive yoga leggings, know you''re not alone. I too believed it to be the fodder of the schedule-free elite, not the likes of me, deep in a grey London winter with a third lockdown looming. However, after months of strength training, cardio home workouts, kettlebell exercises and a smattering of half-hearted yoga, I was craving something different. Something decidedly low-impact. A one-time lover of Reformer Pilates, I looked for similar workouts I could do sans a contraption the size of a small car. Pilates seemed like just the ticket, promising to build core and glute strength, improve posture and sculpt muscle. After two weeks I feel more stable lifting heavy weights, speeding through burpees or performing jump lunges.', 
  'If you''re new to Pilates, a beginner session will be just as challenging as an intermediate workout for those better-versed in the discipline. For activities like barre, Pilates, or light jogging—where your heart rate isn''t as high—your body relies on fat for energy. It makes sense: Fat stays in the body longer than carbs, which is why the body can depend on it for a longer, more steady workout. Combination of low carb and ketogenic diet.',
  'Do 2-3 Pilates sessions a week. Strengthen my core. Try to go to advanced classes and challenge myself.',
  19.5
  ),
  (
  'Nate Dens', 
  'Nate', 
  'Denison', 
  'thedenison@rmx.com', 
  'password', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Man_55_yoga.jpg?raw=true',
  45, 
  'male', 
  72, 
  160, 
  'USA', 
  'maintain', 
  'vegetarian', 
  'yoga', 
  'When I was a teenager, my hamstrings were so tight that it hindered my ability to play baseball, basketball, and soccer. I was really passionate about sports and had tried lots of things to loosen up, and then my mom suggested yoga. I was competitive, so I didn''t like that I couldn''t do a lot of the poses and ended up going back to stretching. After college I moved to New York City and started dating a girl who was really into yoga. She managed a really nice studio, Pure Yoga, and I got to take free classes. The relationship didn''t work out, but I grew my practice from there. Even if I didn''t know what I was doing with my career, my living situation, or my relationship, I could make it to class and practice. Thoughts would come up and I could let go of them, and when class was over, I could leave all of my worries on the mat and walk out the door with a little peace of mind. I might not have all of the answers to my life figured out, but I have a better sense of direction and self-awareness. There is something very powerful about being able to access that. Yoga doesn''t just give you physical flexibility; it gives you mental flexibility. You become open to other ways of thinking or doing things. Now I teach yoga. I still can''t do all of the postures, but I''ve realized that''s not what makes a good teacher. I keep learning.', 
  'You don''t need to count calories religiously or eat bland tasting foods. Follow a whole foods plant-based diet which involves eating a majority of your calories from unprocessed plant foods. Aim for getting 80-90% of your calories from plants. Even if going vegan or vegetarian isn''t your thing, you can aim to eat predominantly unprocessed whole foods along with lean meats and fish. By eating unprocessed, whole foods you will feel more satiated throughout the day and less likely to overeat. ',
  'Train myself with other professionals, to share knowledge with my students. Teach myself a new pose everyday.',
  21.72
  ),
  (
  'Deb Thorton', 
  'Debbie', 
  'Thorton', 
  'thornydeb@golang.ca', 
  'password', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Woman_35_cardio.jpg?raw=true',
  37, 
  'female', 
  66, 
  150, 
  'USA', 
  'weight loss', 
  'paleo', 
  'crossfit', 
  'When I went to college, I gained the typical “freshman 15” and then some. I was chunky. I started playing ultimate frisbee my sophomore year and toned down some, but I''ve always been on the heavy side of fit. At my best, I was around a size 12, and at my worst, up to a size 16. I got married in 1998 and had 3 kids (8, 6, 4, and 2) and had “let myself go”. My lifestyle was sedentary and I wasn''t doing any real form of exercise. I was wearing my stretched out size 14s and honestly, was probably a 16, but refused to shop in that size.   I pretty much avoided the camera. My husband, Mike, has always been in great shape (he''s one of those tall, lean guys who has to work to put on weight) and he had been doing Crossfit for several years at this point.  Frankly, I was sick of hearing him talk about it.  I called him a Crossfit evangelist, because he was always talking it up to people everywhere we went. But, I was getting sick and tired of how I looked and how I felt. I began to feel like if I didn''t do something to take charge of my health, I would lose all hope of ever feeling good about myself. With much trepidation, I showed up on my first crossfit class workout. It was hard, I had to seriously scale it back and I thought I might throw up.  But the feeling I got from completing the workout was addictive. At age 38, I am, by far, in the best shape of my life. My only regret is that I didn''t start sooner.  But I also believe it''s never too late!', 
  'Keep caffeine and coffee to a minimum. Caffeine strips energy from you and enhances cortisol production. Essentially it is one more stressor to add to the stress of training. Make sure to get plenty of omega-3 fats, herbs and spices, fruits and vegetables, and fermented foods. Don''t forget to also take a break when you feel like your body needs it. Don''t indulge yourself with that break though. Keep grinding.',
  'I want to be able to clean and press 135 pounds ten times because it will help push my strength to the next level. I want to gain ten pounds of lean muscle mass.',
  24.23
  ),
  (
  'Manshu Hyas', 
  'Manshu', 
  'Hyas', 
  'hymansh@ind.co', 
  'password', 
  'https://github.com/Joe-Grewal/Uplifting-Feats/blob/main/client/src/images/Man_35_strength.jpg?raw=true',
  24, 
  'male', 
  75, 
  198, 
  'New Zealand', 
  'weight gain', 
  'other', 
  'strength training', 
  'I was really skinny and underweight during half of my life. There were literally no clothes available in my size, hence, I was not able to wear my favourite clothes or the clothes of my liking. It was only when an acquaintance approached me about my weight, that I realized I seriously needed to do something about my health. That was the day I started my fitness journey and I haven''t looked back ever since. I believe that when you have unwavering dedication, you can never really fail. I keep trying and striving for success.', 
  ' Steer clear of processed and packaged food and make sure that you are well-hydrated. Try to meet your daily protein requirements. I workout for 6 days a week and it mostly constitutes of intense weight training sessions. Don''t forget to listen to your body. Slow down if you needed to but don''t lose the ball.',
  '10 years from now, I want to be a fitter and better version of myself.',
  24.77
  )



